sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t surawatthana/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true surawatthana/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "testdockerreact"
  env: "Testdockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-672781813832"
  bucket_path: "testdockerreact"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
